### ISSUE TITLE
Still not able to update, 7 days after release

### ISSUE THREAD

**Issue by teun135** [BSData/warhammer-age-of-sigmar#1671]
Hoping one of you can help me:

I'm still unable to get the repository through Battlescribe, even if I input the file location manually.

I receive this error:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34

Details:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

-------------------- Caused By --------------------

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by cartag** [comment]
Try updating now, just confirmed it's up and I updated my data.
